let stadtData=null;let gutscheinAktiv=!1;document.addEventListener("DOMContentLoaded",()=>{const els={titel:document.getElementById("titel"),land:document.getElementById("land"),preis:document.getElementById("preis"),tage:document.getElementById("tage"),von:document.getElementById("von"),bis:document.getElementById("bis"),personen:document.getElementById("personen"),versicherung:document.getElementById("versicherung"),hotel:document.getElementById("hotel_name"),sterne:document.querySelectorAll("#sterne span"),wifi:document.getElementById("wifi"),pool:document.getElementById("pool"),barriere:document.getElementById("hotel_barriere"),gesamt:document.getElementById("gesamtpreis"),gutschein:document.getElementById("gutschein"),gutscheinBtn:document.getElementById("gutscheinBtn"),buchenBtn:document.getElementById("buchenBtn")};const params=new URLSearchParams(window.location.search);const normalize=(v)=>decodeURIComponent((v||"")).toLowerCase().trim().replace(/\s+/g," ");const urlStadt=normalize(params.get("stadt"));const hotels={"grand hotel":{stars:5,wifi:!0,pool:!1,barrierefrei:!0},"hilton":{stars:5,wifi:!0,pool:!0,barrierefrei:!1},"negresco":{stars:5,wifi:!0,pool:!0,barrierefrei:!0},"premier":{stars:4,wifi:!0,pool:!1,barrierefrei:!1},"world hotels":{stars:4,wifi:!0,pool:!1,barrierefrei:!0}};function setStars(value){const max=els.sterne.length;const full="★".repeat(value);const empty="☆".repeat(max-value);els.sterne.forEach((star,index)=>{star.textContent=index<value?"★":"☆"})}
function syncDateLimits(){const fromDate=els.von.value;if(fromDate){els.bis.min=fromDate}}
function applyHotelFeatures(hotel){const key=(hotel||"").toLowerCase().trim();const data=hotels[key];const star=data?.stars??stadtData?.hotel?.sterne??3;const wifi=data?.wifi??stadtData?.wifi??!1;const pool=data?.pool??stadtData?.pool??!1;const barriere=data?.barrierefrei??stadtData?.transport?.barrierefreundlich??!1;setStars(star);els.wifi.checked=wifi;els.pool.checked=pool;els.barriere.checked=barriere}
function onHotelChange(){applyHotelFeatures(els.hotel.value);updatePrice()}
function parsePreis(t){return parseFloat(String(t).replace(/[^\d.]/g,""))||0}
function getTage(){const d1=new Date(els.von.value);const d2=new Date(els.bis.value);let diff=Math.ceil((d2-d1)/86400000);if(diff<=0)diff=1;els.tage.textContent=diff;return diff}
function updatePrice(){if(!stadtData)return;const personen=+els.personen.value||1;const versicherung=+els.versicherung.value||0;const base=parsePreis(stadtData.preis);const baseDay=base/(stadtData.dauer_tage||1);const hotelPreis=+els.hotel.selectedOptions[0]?.dataset?.preis||0;let total=(baseDay+hotelPreis)*getTage()*personen+versicherung*personen;if(els.gutschein.value.trim()==="90439"||gutscheinAktiv){total*=0.561;gutscheinAktiv=!0;els.gutscheinBtn.disabled=!0;els.gutschein.disabled=!0;els.gutschein.value="90439 ✔"}else{els.gutscheinBtn.disabled=!1;els.gutschein.disabled=!1;els.gutschein.value=els.gutschein.value.replace(" ✔","")}
els.gesamt.textContent=total.toFixed(2)}
function checkChallenge(){const urlParams=new URLSearchParams(window.location.search);const urlStadt=normalize(urlParams.get("stadt"));const urlPreis=urlParams.get("preis");const urlTage=urlParams.get("tage");const personen=+els.personen.value;const versicherung=els.versicherung.value;const gutschein=els.gutschein.value.trim();const hotelText=els.hotel.selectedOptions[0]?.textContent||"";const hotelClean=hotelText.toLowerCase();const expectedVonDate="2026-06-01";const expectedBisDate="2026-06-06";const isNegresco=hotelClean.includes("negresco");if(urlStadt==="verona"&&urlPreis==="980"&&urlTage==="4"&&personen===4&&versicherung==="80"&&isNegresco&&gutschein==="90439 ✔"&&els.von.value===expectedVonDate&&els.bis.value===expectedBisDate){return!0}
return!1}
fetch("staedte.json").then(r=>r.json()).then(data=>{stadtData=data.find(s=>normalize(s.name)===urlStadt);if(!stadtData){document.body.innerHTML="<h2>Stadt nicht gefunden</h2>";return}
els.titel.textContent=stadtData.name;els.land.textContent=stadtData.land;els.preis.textContent=stadtData.preis;const dauer=stadtData.transport.flugzeit??stadtData.transport.fahrzeit??"unbekannter Dauer";document.getElementById("transport").textContent=`Die Anreise erfolgt mit ${stadtData.transport.typ} und dauert etwa ${dauer}.`;document.getElementById("barrierefrei").checked=stadtData.transport.barrierefreundlich;document.getElementById("rollstuhl").checked=stadtData.transport.rollstuhl_möglich;els.von.value=stadtData.zeitraum.von;els.bis.value=stadtData.zeitraum.bis;syncDateLimits();els.personen.value=1;els.hotel.innerHTML=`
  <option value="grand hotel" data-preis="0">${stadtData.hotel.hotel_name}</option>
  <option value="grand hotel" data-preis="200">Grand Hotel (zzgl. 200 € / Nacht & Person)</option>
  <option value="hilton" data-preis="300">Hilton (zzgl. 300 € / Nacht & Person)</option>
  <option value="negresco" data-preis="250">Negresco (zzgl. 250 € / Nacht & Person)</option>
  <option value="premier" data-preis="150">Premier (zzgl. 150 € / Nacht & Person)</option>
  <option value="world hotels" data-preis="180">World Hotels (zzgl. 180 € / Nacht & Person)</option>
`;els.hotel.addEventListener("change",onHotelChange);els.von.addEventListener("input",()=>{syncDateLimits();updatePrice()});els.bis.addEventListener("input",updatePrice);els.personen.addEventListener("input",updatePrice);els.versicherung.addEventListener("change",updatePrice);els.gutscheinBtn.addEventListener("click",updatePrice);els.buchenBtn.addEventListener("click",()=>{if(checkChallenge()){window.location.href="challengedone.html"}else{alert("Aufgaben nicht erfüllt.")}});els.hotel.selectedIndex=0;onHotelChange();updatePrice()})})